### ISSUE TITLE
Subsupport integration

### ISSUE THREAD

**Issue by oxejatte** [j00zek/FreePlayer#2]
Thank you for this great player

Do you plan to integrate Subsupport ( https://github.com/mx3L/subssupport ) in future versions ?
Tags in subtitles are not handled (italic,bold,color) by the player, benefit would be lighter code and keys handling subtitles could be reassigned for better purpose, example missing key assignment for aspect ratio change witch is very important in some boxes ( i have a Sti7111 box). 

Regards

**Comment by oxejatte** [comment]
Hi,

I've managed to integrate Subssupport, and made some modifications for enabling changing aspect ratio and reassign keys to handle all that, changes are made also to change the extension description from txt to nfo (conflict with txt subtiles)
Changes are on AdvancedFreePlayer.py, Keymap.xml and made my own skin on MetrixHD so everything is perfect now, just waiting for info and cover download
Unfortunatly every time i tried to upload modified files (zip,txt) here i've got an error message on Github
"Something went really wrong, and we can’t process that file. "

Just wanted to share my modifications is there another way to do that ?

Regards

**Comment by j00zek** [comment]
You need to fork the repository, make changes on it and create pull request. I will be able then to merge them with original code.

**Comment by oxejatte** [comment]
Ok i finally managed to attach modified files, i'm just discovering Github ;-)

Changes are commented

[AdvancedFreePlayer.zip](https://github.com/j00zek/FreePlayer/files/62991/AdvancedFreePlayer.zip)

My Skin is MetrixHD_MOD ( http://forums.openpli.org/topic/27010-metrixhd-mod-by-taykun345/ ) here are the two screens

<screen name="AdvancedFreePlayerStart" position="-2,-1" size="1314,723" title=" " flags="wfNoBorder" backgroundColor="transparent">
    <eLabel position="503,24" zPosition="-10" size="765,645" backgroundColor="background20" />
    <eLabel position="17,24" zPosition="-10" size="480,560" backgroundColor="background20" />
    <widget name="filelist" position="507,76" size="755,326" font="Regular;20" foregroundColor="unffffff" backgroundColor="un444444" transparent="1" halign="left" valign="top" />
    <ePixmap name="new ePixmap" position="1175,630" size="81,40" pixmap="MetrixHD_MOD/buttons/key_menu.png" />
    <ePixmap pixmap="MetrixHD_MOD/buttons/red.png" position="505,630" size="30,40" alphatest="blend" />
    <ePixmap pixmap="MetrixHD_MOD/buttons/green.png" position="672,630" size="30,40" alphatest="blend" />
    <ePixmap pixmap="MetrixHD_MOD/buttons/yellow.png" position="831,630" size="30,40" alphatest="blend" />
    <ePixmap pixmap="MetrixHD_MOD/buttons/blue.png" position="986,630" size="30,40" alphatest="blend" />
    <widget source="key_red" render="Label" position="543,630" size="140,24" zPosition="1" font="Regular; 20" halign="left" backgroundColor="un444444" transparent="1" />
    <widget source="key_green" render="Label" position="712,630" size="140,24" zPosition="1" font="Regular; 20" halign="left" backgroundColor="un444444" transparent="1" />
    <widget source="key_yellow" render="Label" position="869,630" size="130,24" zPosition="1" font="Regular; 20" halign="left" backgroundColor="un444444" transparent="1" />
    <widget source="key_blue" render="Label" position="1026,630" size="130,24" zPosition="1" font="Regular; 20" halign="left" backgroundColor="un444444" transparent="1" />
    <widget source="global.CurrentTime" render="Label" position="174,590" size="180,80" font="Regular; 60" halign="left" backgroundColor="un444444" transparent="1" valign="top">
      <convert type="ClockToText">Default</convert>
    </widget>
    <widget source="global.CurrentTime" render="Label" position="-2,632" size="148,29" font="Regular; 20" halign="right" backgroundColor="un444444" foregroundColor="grey" transparent="1">
      <convert type="ClockToText">Format:%e. %B</convert>
    </widget>
    <widget source="global.CurrentTime" render="Label" position="23,602" size="125,30" font="Regular; 20" halign="right" backgroundColor="un444444" foregroundColor="grey" transparent="1">
      <convert type="ClockToText">Format:%A</convert>
    </widget>
    <eLabel position="20,600" zPosition="-1" size="340,70" backgroundColor="background20" transparent="0" />
    <widget name="Cover" position="95,102" size="320,351" pixmap="MetrixHD_MOD/icons/media.png" transparent="1" alphatest="blend" zPosition="4" />
    <widget name="Description" options="movetype=running,startpoint=0,direction=top,steptime=100,startdelay=3000,wrap,always=0" render="RunningText" position="507,412" size="755,200" font="Regular; 19" foregroundColor="unffffff" backgroundColor="un444444" transparent="1" halign="left" valign="top" />
    <widget name="myPath" position="507,28" size="755,40" font="Regular; 19" foregroundColor="grey" halign="left" backgroundColor="un444444" transparent="1" />
    <widget name="filemovie" render="Label" position="52,510" size="430,30" font="Regular;18" foregroundColor="unffffff" backgroundColor="un444444" valign="top" halign="left" transparent="1" zPosition="-9" />
    <widget name="filesubtitle" position="52,549" size="430,30" font="Regular; 18" foregroundColor="unffffff" backgroundColor="un444444" valign="top" halign="left" transparent="1" zPosition="-9" />
    <ePixmap pixmap="MetrixHD_MOD/icons/video.png" position="25,512" size="25,25" alphatest="blend" />
    <ePixmap pixmap="MetrixHD_MOD/icons/texte.png" position="25,549" size="25,25" alphatest="blend" />
  </screen>
<screen name="AdvancedFreePlayerInfobar" position="-1,0" size="1280,92" title=" " backgroundColor="transparent" flags="wfNoBorder" alphatest="on"> 
    <widget source="session.CurrentService" render="Label" position="1098,8" size="60,25" font="Regular; 20" halign="right" foregroundColor="foreground" backgroundColor="background" transparent="1">
      <convert type="ServiceInfo">VideoWidth</convert>
    </widget>
    <eLabel text="X" position="1109,13" size="60,30" font="Regular; 16" halign="right" foregroundColor="foreground" backgroundColor="background" transparent="1" />
    <widget source="session.CurrentService" render="Label" position="1171,8" size="60,25" font="Regular; 20" halign="left" foregroundColor="foreground" backgroundColor="background" transparent="1" valign="center" zPosition="0">
      <convert type="ServiceInfo">VideoHeight</convert>
    </widget>    
    <ePixmap pixmap="MetrixHD_MOD/infobar_movie.png" position="-1,-2" zPosition="-2" size="1281,92" alphatest="off" />
    <widget source="session.CurrentService" render="Label" position="149,9" size="945,50" font="Regular; 30" valign="top" backgroundColor="background20" transparent="1">
      <convert type="ServiceName">Name</convert>
    </widget>
    <ePixmap pixmap="MetrixHD_MOD/icons/ico_hd_off.png" position="1098,40" size="41,20" zPosition="1" alphatest="blend" />
    <widget source="session.CurrentService" render="Pixmap" position="1098,40" size="41,20" zPosition="2" pixmap="MetrixHD_MOD/icons/ico_hd_on.png" alphatest="blend">
      <convert type="ServiceInfo">VideoWidth</convert>
      <convert type="ValueRange">721,1980</convert>
      <convert type="ConditionalShowHide" />
    </widget>
    <ePixmap pixmap="MetrixHD_MOD/icons/ico_dolby_off.png" position="1180,40" size="56,20" zPosition="1" alphatest="blend" />
    <widget source="session.CurrentService" render="Pixmap" pixmap="MetrixHD_MOD/icons/ico_dolby_on.png" position="1180,40" size="56,20" zPosition="2" alphatest="blend">
      <convert type="ServiceInfo">IsMultichannel</convert>
      <convert type="ConditionalShowHide" />
    </widget>
    <ePixmap pixmap="MetrixHD_MOD/icons/ico_format_off.png" position="1144,40" size="32,20" zPosition="1" alphatest="blend" />
    <widget source="session.CurrentService" render="Pixmap" pixmap="MetrixHD_MOD/icons/ico_format_on.png" position="1144,40" size="32,20" zPosition="2" alphatest="blend">
      <convert type="ServiceInfo">IsWidescreen</convert>
      <convert type="ConditionalShowHide" />
    </widget>   
    <widget source="session.CurrentService" render="Label" position="40,58" size="100,28" font="Regular;24" halign="right" valign="center" backgroundColor="background20" shadowColor="black" shadowOffset="-1,-1" transparent="1">
      <convert type="ServicePosition">Position</convert>
    </widget>
    <widget source="session.CurrentService" render="PositionGauge" position="150,72" size="860,9" transparent="1">
      <convert type="ServicePosition">Gauge</convert>
    </widget>
    <widget source="session.CurrentService" render="Progress" position="150,75" size="860,3" pixmap="MetrixHD_MOD/p_bar_A.png" borderWidth="0" transparent="1" backgroundColor="metrixAccent">
      <convert type="ServicePosition">Position</convert>
    </widget>
    <widget source="session.CurrentService" render="Label" position="1018,58" size="100,28" font="Regular;24" halign="left" valign="center" backgroundColor="background20" transparent="1">
      <convert type="ServicePosition">Remaining</convert>
    </widget>
    <widget source="session.CurrentService" render="Label" position="3,9" size="137,50" font="Regular; 30" halign="right" valign="top" backgroundColor="background20" transparent="1" foregroundColor="metrixAccent">
      <convert type="ServicePosition">Length</convert>
    </widget>
    <eLabel name="new eLabel" position="150,76" size="860,1" backgroundColor="grey" foregroundColor="grey" zPosition="-1" />  
</screen>

**Comment by oxejatte** [comment]
Sorry i forget
Green button : Change Aspect Ratio
Yellow Button : Subssupport
P+/P- : Seek +/- Subtitles
Fast Forward/Backward : Jump to a position in movie

**Comment by j00zek** [comment]
thanks, your changes interfere with standard player functionality, they need some investment in time to merge, but definitevely will do it.

**Comment by oxejatte** [comment]
Thank you

I think the best way to minimize the interferences is to let the choice to the user to integrate or not Subssupport in config ( SRT subtitles displayed by : Plugin/System/Subsupport ) this is what i was planning to do.
For future developments I've also thinking about custom audio panel (because of multi-tracks ) without system subtitles settings (now with red button it's standard audio panel) then disabling or not infobar at start in config and show cover & description while playing movie with EPG button.
 
Anyway your player still the best i ever see especially on low memory boxes like mine.

**Comment by oxejatte** [comment]
Good job J00zek with the last release, i like the new philosophy ;-)
I've got a GS every time i tried to read a video.
Here's the log : 
-----------------------------------------------------------------------------------------------------------
[AdvancedFreePlayer] LoadSkin >>> AdvancedFreePlayerInfobar
[AdvancedFreePlayer] LoadSkin >>> AdvancedFreePlayerLCD
[AdvancedFreePlayer] AdvancedFreePlayerLCD does not exists
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/AdvancedFreePlayer/AFPtreeSelector.py", line 233, in playORdelete
    self.PlayMovie()
  File "/usr/lib/enigma2/python/Plugins/Extensions/AdvancedFreePlayer/AFPtreeSelector.py", line 263, in PlayMovie
    self.SelectFramework()
  File "/usr/lib/enigma2/python/Plugins/Extensions/AdvancedFreePlayer/AFPtreeSelector.py", line 283, in SelectFramework
    self.StartPlayer()
  File "/usr/lib/enigma2/python/Plugins/Extensions/AdvancedFreePlayer/AFPtreeSelector.py", line 315, in StartPlayer
    self.session.openWithCallback(EndPlayer,AdvancedFreePlayer,self.openmovie,self.opensubtitle,self.rootID,self.LastPlayedService,self.URLlinkName, self.movieTitle)
  File "/usr/lib/enigma2/python/mytest.py", line 274, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 284, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 228, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 244, in doInstantiateDialog
    dlg = screen(self, *arguments, **kwargs)
TypeError: __init__() takes at most 7 arguments (8 given)
<189500.906073> [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2dc75c6c>>,('AdvancedFreePlayerSelector', 'playORdelete')) failed)
]]>
		</enigma2crashlog>
	</crashlogs>
</openpli>

**Comment by j00zek** [comment]
hopefully fixed
